title: Pre-CHI 2025
preposition: ''
description: >-
  South West UK Pre-CHI Event is to provide an opportunity for researchers from the South West England and De Cymru Human-Computer Interaction Community (SWEDC-HCI) to come together to practice running their accepted CHI papers and work-in-progress research talks
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://South-West-UK-Pre-CHI.github.io" # the base hostname & protocol for your site, e.g. https://example.com
favicon: "/assets/images/favicon.ico"

# Build settings
markdown: kramdown
sass:
  style: compressed

# Additional exclude from processing
exclude:
  - vendor
  - .github/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - purgecss.config.js

# Collections and their defaults
collections:
  talks:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room


conference:

  # Language
  lang: en

  # Timezone
  tz: "+00:00"

  # Show theme errors:
  show_errors: True

  # Navigation bar
  navigation:
    logo:
      name: SWEDC-HCI
      # img: ''
      url: 'https://gw4.ac.uk/community/south-west-england-and-de-cymru-human-computer-interaction-community-swedc-hci/'
    breakpoint: md
    links:
      - name: Programme
        relative_url: /programme/
      - name: Talks
        relative_url: /talks/
      - name: Speakers
        relative_url: /speakers/
      - name: Location
        relative_url: /location/
      - name: Funders
        relative_url: /funders/
      - name: Organisers
        relative_url: /organisers/
      - name: Opportunities
        relative_url: /opportunities/
      - name: Previous Editions
        menu:
          - name: 2025 (current)
            disabled: true
          - name: 2024
            relative_url: /2024/

  # Link Preview for Sharing
  link_preview:
    # also adapt "preposition" property at top for more meaningful descriptions
    disable: false
    img:
      twitter: 'twitter_preview.png'      # inside /assets/images/
      open_graph: 'facebook_preview.png'  # inside /assets/images/

  # Main landing page
  main:
    logo:
      img: 'logo.png'  # inside /assets/images/
    links:
      - name: Registration
        disabled: false
        absolute_url: 'https://forms.office.com/Pages/ResponsePage.aspx?id=MH_ksn3NTkql2rGM8aQVG071U7kgyVNHkjE1q_ZcfuxUOVdOQVdFT1ExWDVROFYwWUVRMVhTUFNDVS4u'
      - name: Programme
        relative_url: /programme/
      - name: How to get there
        relative_url: /location/


  # Information boxes
  info_bars:
    - title: Applications for Talks now closed!
      color: primary
      main_only: true
      text: |
        Thank you to all speakers for submitting their talks!

  # Live indications
  live:
    date: 01.01.2020
    timezone: GMT
    stop:       240  # in minutes
    streaming:
      enable: true
      pause:     60  # in minutes
      prepend:    5  # in minutes
      extend:     5  # in minutes
    demo:
      enable: false
      duration: 300  # in seconds
      pause:     10  # in seconds

  talks:
    # Talk categories
    main_categories:
      - name: Talk Category 1
        color: secondary
      - name: Talk Category 2
        color: success
      - name: Talk Category 3
        color: info
      - name: Talk Category 4
        color: warning
      - name: Doctoral Consortium
        color: danger
      - name: Workshops/Demos
        color: primary
      - name: Other (coffee etc.)
        color: primary
    # Hide icons on talk overview page
    hide_icons: false

  speakers:
    # Show first and last name
    show_firstname: true

  location:
    # Disable links to locations
    hide: false
    # URL of location / room overview page
    url: '/location'
    # Main page title shown on location/room navigation bar
    navbar_title: 'Location'
    # Show map on location main page.  Set `map: false` if you don't want to
    # display it.
    map:
      # Initial map center point
      home_coord: 51.456384761892366, -2.6047370079301566
      # Alternative map providers can be found on https://leaflet-extras.github.io/leaflet-providers/preview/
      # The following do match the Bootstrap design not too badly:
      #   - Thunderforest.Neighbourhood
      #   - Esri.WorldTopoMap
      map_provider: "OpenStreetMap.Mapnik"
      default_zoom: 17


  program:
    # URL of programme page
    url: '/programme'

    # Time steps in programme table
    time_steps: 15 # in minutes

    # Show intermediary time steps (next to full hours)
    show_alltimes: true
